export enum AuthMutationTypes {
  FORM_EMAIL = "AUTH_FORM__EMAIL",
  FORM_USERNAME = "AUTH_FORM__USERNAME",
  FORM_PASSWORD = "AUTH_FORM__PASSWORD",
  FORM_CONFIRM_PASSWORD = "AUTH_FORM__CONFIRM_PASSWORD",
  SESSION_EXP = "AUTH__SESSION_EXP",
}
