#index:
#    path: /
#    controller: App\Controller\DefaultController::index

frontend_index:
    path: '/{req}'
    defaults: { _controller: App\Controller\FrontendController::index }
    requirements:
        req: "^((?!api).)*$"